os: linux
dist: trusty
cache: false
sudo: required
language: bash
services: docker
env:
  matrix:
  - ARCH=x86_64 PUID=1000 PGID=1000
  - ARCH=armhf PUID=1001 PGID=1001
  global:
  - secure: rQFdbQm+UUvWaAf53PAcN3inbmjz1AuKMBwjGOs3f/JPy7KsDzkoySVqClsBMZ4cmOyGU5C2PoYn0XZ+WJJKhOLfipifltzp5If2pddsGi8kI6Bk9T7wuYbHllikRgyZhB7A00L8TrNiWv626uk8xYetlFGFX6QpBDLioPbAKPDnyYOIJE0wbdhlEV+Z2A8lGglEyiVATisgm1xS2YDZnE+DM2qqSgwcjqFibgu2g/1WAls/g7HbeZxWTngYQ6cyVkB1PdlTGu6MPd5Phs1dRdg8yh006rdh7N5/T/9fjNqWGRFU8EosbVPF8gW74c6rsTJf9cfIBR+ZLLbbysF4hLnKcIiMvZ4ASgRgD3D9RfwP5bpjXzDaBXPlY1osSgDnTSpJHnKE++5e8N5rskGe42omnt/t4SUCt8I74AZv8VHS+9cBJNaLbi8ypTUhIh1ti9bcdMB3OToyhGe/gVv3kMaONiWUYdQ9ijom06F5urHf/HL4NUFFfbuLkjJfrEGZCC/vTueJ1tXwGrVdekvmQIePnd7Wyvut40HpJaub18g46QAD8Rd9OdfsH8uZPBV7l/9JzCZhmP/eK72px8ZtI7bkm/9Hlx3BrrTU/qvMAfKc2VZdFlGDr+YbVekhvgMsGOxVsvrt4pKB9OxZv2gCNz6ZiJ7zq/reIJWHhJOaxqc=
  - secure: e1pA6d5Tqd+WZgRB2S76iuGT6kR37NdueG/mIVR660Oa/P5HBCScX5XUJ4f1zgQXIxIfL2ySrS/yzh5mnPpiaRkxyDdO5MeNRYVehtdGck2TmRLaoUfAD3QdoK6L0yqf20+6RqqwzsYmqVsFCdywdLz//3TeTFjHQJzrUacPTO7LFPsOypZxbJgsgN4VyHL8DnLP+M94qGDs9xIxbpNUla3kxPSa8NqdHD8sSh4ymz0MKa1o24R+8zIgtAAaVIoWH5eYGTza7RD225tZInmvxj+NysykSI+ZVU6BnOBH3m9I7zj9LyXEtjdMuysMDDMLGlQ7sCRYlSW2Jac9roOIgxYl0jKMbDsfwFTna4f3US0v4lh2BZlQ1N4iSr0xlcSTKekuqSs3MzTOmrL85WvvatFD/17hKh0irc3+CHsof3QOmGTSYwt0ENdUha1C7j10Q9gMKgw27cdbetkWX8EGFVx5BHZLvw4Pqv+A979lJi/dQrJYsqyCscKjUvnUFUyBRD9LTn6NRpOXtXXBwWSMwQVu+QxPF6WV2nZYnvpKX5tNBYkWiKpROkrS7HQdYHh2+a6V/lUSqOLKb7RQZcqQ3jUzrEemAg0BbEJFnv/CTV2xtREvE+395jHZf7UJnECkx3aGpIBwzVbDN973+FQsdnLG0vT9Ji3z+/45tCcxdLg=
install: true
before_script:
- docker --version
- make --version
script:
- make ARCH=${ARCH} PUID=${PUID} PGID=${PGID} build test
after_success:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- make ARCH=${ARCH} push
after_script:
- docker logout
- make clean
